### PR TITLE
fixes various issues with the new session title input.

### LINKED ISSUE #1794: new session: typing in title input field throws error
Selection_061

add integration test for the new session component while at it.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #1794

### CODE REVIEW

File: addon-test-support/ilios-common/page-objects/sessions.js [hunk 1]
```diff
@@ -7,20 +7,22 @@ import {
...
   showsAllSessionsExpanded: hasClass('fa-caret-down', '[data-test-expand-all] svg'),
   expandNewSessionForm: clickable('[data-test-actions] [data-test-expand-collapse-button] button'),
-  newSession: {
-    scope: '[data-test-new-session]',
-    title: fillable('[data-test-title]'),
-    type: fillable('[data-test-type]'),
-    save: clickable('[data-test-save]'),
-    cancel: clickable('[data-test-cancel]'),
-  },
+  // newSession: {
```
Comment (jrjohnson) [inline addon-test-support/ilios-common/page-objects/sessions.js:18]: Would prefer not to leave in commented code.

**Review by jrjohnson — CHANGES_REQUESTED** [review]

File: addon-test-support/ilios-common/page-objects/sessions.js (hunk 1 above)
Comment (stopfstedt) [reply addon-test-support/ilios-common/page-objects/sessions.js:18]: me too. removed.

**Review by jrjohnson — APPROVED** [review]
